SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS SA SALT 'a13d5da1c1edca39' HASH '0ec74910d398509bca3c28e42683ebfc07f6756d0329f5065d1c774bf3c1c54d' ADMIN;

CREATE SEQUENCE PUBLIC.ORGANIZATION_SEQUENCE START WITH 1;
CREATE SEQUENCE PUBLIC.EVENT_SEQUENCE START WITH 1;
CREATE SEQUENCE PUBLIC.VOLUNTEEREVENT_SEQUENCE START WITH 1;

CREATE MEMORY TABLE PUBLIC.PERSON(
    P_EMAIL VARCHAR(255) NOT NULL,
    P_FIRSTNAME VARCHAR(255) NOT NULL,
    P_LASTNAME VARCHAR(255) NOT NULL,
    P_ADDRESS VARCHAR(255),
    P_CITY VARCHAR(255),
    P_STATE VARCHAR(2),
    P_ZIP VARCHAR(5),
    P_DOB DATE NOT NULL
);               
ALTER TABLE PUBLIC.PERSON ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(P_EMAIL);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PERSON;   
CREATE MEMORY TABLE PUBLIC.VOLUNTEER(
    V_EMAIL VARCHAR(255) NOT NULL
);     
ALTER TABLE PUBLIC.VOLUNTEER ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(V_EMAIL);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VOLUNTEER;
CREATE MEMORY TABLE PUBLIC.STUDENT(
    S_EMAIL VARCHAR(255) NOT NULL,
    S_SCHOOL VARCHAR(255) NOT NULL,
    S_MAJOR VARCHAR(255) NOT NULL,
    S_GRADYEAR INTEGER NOT NULL,
    S_ID VARCHAR(255) NOT NULL
);               
ALTER TABLE PUBLIC.STUDENT ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(S_EMAIL);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.STUDENT;  
CREATE MEMORY TABLE PUBLIC.AVAILABLETIME(
    AT_VOLUNTEER VARCHAR(255) NOT NULL,
    AT_STARTTIME DATETIME NOT NULL,
    AT_ENDTIME DATETIME NOT NULL
);      
ALTER TABLE PUBLIC.AVAILABLETIME ADD CONSTRAINT PUBLIC.CONSTRAINT_29 PRIMARY KEY(AT_VOLUNTEER, AT_STARTTIME, AT_ENDTIME);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.AVAILABLETIME;            
CREATE MEMORY TABLE PUBLIC.WORKER(
    W_EMAIL VARCHAR(255) NOT NULL,
    W_POSITION VARCHAR(255)
);           
ALTER TABLE PUBLIC.WORKER ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(W_EMAIL);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.WORKER;   
CREATE MEMORY TABLE PUBLIC.LOGIN(
    L_EMAIL VARCHAR(255) NOT NULL,
    L_PASSWORD VARCHAR(255),
    L_HASH VARCHAR(255)
);   
ALTER TABLE PUBLIC.LOGIN ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(L_EMAIL);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LOGIN;    
CREATE MEMORY TABLE PUBLIC.ORGANIZATION(
    O_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.ORGANIZATION_SEQUENCE) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.ORGANIZATION_SEQUENCE,
    O_NAME VARCHAR(255) NOT NULL,
    O_DESCRIPTION VARCHAR(255),
    O_ADDRESS VARCHAR(255) NOT NULL,
    O_CITY VARCHAR(255) NOT NULL,
    O_STATE VARCHAR(2) NOT NULL,
    O_ZIP VARCHAR(5) NOT NULL,
    O_ORGANIZER VARCHAR(255) NOT NULL
);          
ALTER TABLE PUBLIC.ORGANIZATION ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(O_ID);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORGANIZATION;             
CREATE MEMORY TABLE PUBLIC.TAG(
    T_NAME VARCHAR(255) NOT NULL
);            
ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(T_NAME); 
-- 36 +/- SELECT COUNT(*) FROM PUBLIC.TAG;     
INSERT INTO PUBLIC.TAG(T_NAME) VALUES
('Advocacy'),
('Arts'),
('Cooperative Business'),
('Counseling'),
('Crisis Intervention'),
('Culture'),
('Disabilities'),
('Disaster Relief'),
('Domestic Violence'),
('Economic Justice'),
('Education'),
('Elderly'),
('Emergency Assistance'),
('Environment'),
('Financial Counseling'),
('Healthcare'),
('History'),
('Homelessness'),
('Housing'),
('Human Rights'),
('Immigration'),
('Literacy'),
('Mental Health'),
('Mentoring'),
('Nature'),
('Nutrition'),
('Poverty'),
('Recreation'),
('Senior Services'),
('Social Justice'),
('Substance Abuse'),
('Tutoring'),
('Veterans Issues'),
('Women''s issues'),
('Youth'),
('TestingAddTag');  
CREATE MEMORY TABLE PUBLIC.ORGANIZATIONTAG(
    OT_ORGANIZATION INTEGER NOT NULL,
    OT_TAG VARCHAR(255) NOT NULL
);          
ALTER TABLE PUBLIC.ORGANIZATIONTAG ADD CONSTRAINT PUBLIC.CONSTRAINT_91 PRIMARY KEY(OT_ORGANIZATION, OT_TAG);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORGANIZATIONTAG;          
CREATE MEMORY TABLE PUBLIC.VOLUNTEERTAG(
    VT_VOLUNTEER VARCHAR(255) NOT NULL,
    VT_TAG VARCHAR(255) NOT NULL
);           
ALTER TABLE PUBLIC.VOLUNTEERTAG ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(VT_VOLUNTEER, VT_TAG);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VOLUNTEERTAG;             
CREATE MEMORY TABLE PUBLIC.EVENT(
    E_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.EVENT_SEQUENCE) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.EVENT_SEQUENCE,
    E_DATETIME DATETIME NOT NULL,
    E_NAME VARCHAR(255) NOT NULL,
    E_DESCRIPTION VARCHAR(255),
    E_ORGANIZATION INTEGER NOT NULL,
    E_EMPLOYEEORG VARCHAR(255)
);        
ALTER TABLE PUBLIC.EVENT ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(E_ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EVENT;    
CREATE MEMORY TABLE PUBLIC.VOLUNTEEREVENT(
    VE_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.VOLUNTEEREVENT_SEQUENCE) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.VOLUNTEEREVENT_SEQUENCE,
    VE_VOLUNTEER VARCHAR(255) NOT NULL,
    VE_EVENT INTEGER NOT NULL,
    VE_HOURS INTEGER NOT NULL
); 
ALTER TABLE PUBLIC.VOLUNTEEREVENT ADD CONSTRAINT PUBLIC.CONSTRAINT_1A PRIMARY KEY(VE_ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VOLUNTEEREVENT;           
ALTER TABLE PUBLIC.EVENT ADD CONSTRAINT PUBLIC.CONSTRAINT_3F4 FOREIGN KEY(E_EMPLOYEEORG) REFERENCES PUBLIC.WORKER(W_EMAIL) CHECK;
ALTER TABLE PUBLIC.STUDENT ADD CONSTRAINT PUBLIC.CONSTRAINT_BA FOREIGN KEY(S_EMAIL) REFERENCES PUBLIC.VOLUNTEER(V_EMAIL) CHECK;
ALTER TABLE PUBLIC.LOGIN ADD CONSTRAINT PUBLIC.CONSTRAINT_45 FOREIGN KEY(L_EMAIL) REFERENCES PUBLIC.PERSON(P_EMAIL) CHECK;
ALTER TABLE PUBLIC.ORGANIZATIONTAG ADD CONSTRAINT PUBLIC.CONSTRAINT_91A8 FOREIGN KEY(OT_ORGANIZATION) REFERENCES PUBLIC.ORGANIZATION(O_ID) CHECK;
ALTER TABLE PUBLIC.VOLUNTEER ADD CONSTRAINT PUBLIC.CONSTRAINT_27 FOREIGN KEY(V_EMAIL) REFERENCES PUBLIC.PERSON(P_EMAIL) CHECK;
ALTER TABLE PUBLIC.AVAILABLETIME ADD CONSTRAINT PUBLIC.CONSTRAINT_297 FOREIGN KEY(AT_VOLUNTEER) REFERENCES PUBLIC.VOLUNTEER(V_EMAIL) CHECK;
ALTER TABLE PUBLIC.VOLUNTEERTAG ADD CONSTRAINT PUBLIC.CONSTRAINT_C49 FOREIGN KEY(VT_TAG) REFERENCES PUBLIC.TAG(T_NAME) CHECK;
ALTER TABLE PUBLIC.VOLUNTEERTAG ADD CONSTRAINT PUBLIC.CONSTRAINT_C4 FOREIGN KEY(VT_VOLUNTEER) REFERENCES PUBLIC.VOLUNTEER(V_EMAIL) CHECK;
ALTER TABLE PUBLIC.VOLUNTEEREVENT ADD CONSTRAINT PUBLIC.CONSTRAINT_1A1 FOREIGN KEY(VE_VOLUNTEER) REFERENCES PUBLIC.VOLUNTEER(V_EMAIL) CHECK;
ALTER TABLE PUBLIC.ORGANIZATION ADD CONSTRAINT PUBLIC.CONSTRAINT_D0 FOREIGN KEY(O_ORGANIZER) REFERENCES PUBLIC.WORKER(W_EMAIL) CHECK;
ALTER TABLE PUBLIC.WORKER ADD CONSTRAINT PUBLIC.CONSTRAINT_98 FOREIGN KEY(W_EMAIL) REFERENCES PUBLIC.PERSON(P_EMAIL) CHECK;
ALTER TABLE PUBLIC.VOLUNTEEREVENT ADD CONSTRAINT PUBLIC.CONSTRAINT_1A13 FOREIGN KEY(VE_EVENT) REFERENCES PUBLIC.EVENT(E_ID) CHECK;
ALTER TABLE PUBLIC.ORGANIZATIONTAG ADD CONSTRAINT PUBLIC.CONSTRAINT_91A FOREIGN KEY(OT_TAG) REFERENCES PUBLIC.TAG(T_NAME) CHECK;
ALTER TABLE PUBLIC.EVENT ADD CONSTRAINT PUBLIC.CONSTRAINT_3F FOREIGN KEY(E_ORGANIZATION) REFERENCES PUBLIC.ORGANIZATION(O_ID) CHECK;
