-- TAGS

INSERT INTO TAG(T_NAME) VALUES ('Advocacy');
INSERT INTO TAG(T_NAME) VALUES ('Arts');
INSERT INTO TAG(T_NAME) VALUES ('Cooperative Business');
INSERT INTO TAG(T_NAME) VALUES ('Counseling');
INSERT INTO TAG(T_NAME) VALUES ('Crisis Intervention');
INSERT INTO TAG(T_NAME) VALUES ('Culture');
INSERT INTO TAG(T_NAME) VALUES ('Disabilities');
INSERT INTO TAG(T_NAME) VALUES ('Disaster Relief');
INSERT INTO TAG(T_NAME) VALUES ('Domestic Violence');
INSERT INTO TAG(T_NAME) VALUES ('Economic Justice');
INSERT INTO TAG(T_NAME) VALUES ('Education');
INSERT INTO TAG(T_NAME) VALUES ('Elderly');
INSERT INTO TAG(T_NAME) VALUES ('Emergency Assistance');
INSERT INTO TAG(T_NAME) VALUES ('Environment');
INSERT INTO TAG(T_NAME) VALUES ('Financial Counseling');
INSERT INTO TAG(T_NAME) VALUES ('Healthcare');
INSERT INTO TAG(T_NAME) VALUES ('History');
INSERT INTO TAG(T_NAME) VALUES ('Homelessness');
INSERT INTO TAG(T_NAME) VALUES ('Housing');
INSERT INTO TAG(T_NAME) VALUES ('Human Rights');
INSERT INTO TAG(T_NAME) VALUES ('Immigration');
INSERT INTO TAG(T_NAME) VALUES ('Literacy');
INSERT INTO TAG(T_NAME) VALUES ('Mental Health');
INSERT INTO TAG(T_NAME) VALUES ('Mentoring');
INSERT INTO TAG(T_NAME) VALUES ('Nature');
INSERT INTO TAG(T_NAME) VALUES ('Nutrition');
INSERT INTO TAG(T_NAME) VALUES ('Poverty');
INSERT INTO TAG(T_NAME) VALUES ('Recreation');
INSERT INTO TAG(T_NAME) VALUES ('Senior Services');
INSERT INTO TAG(T_NAME) VALUES ('Social Justice');
INSERT INTO TAG(T_NAME) VALUES ('Substance Abuse');
INSERT INTO TAG(T_NAME) VALUES ('Tutoring');
INSERT INTO TAG(T_NAME) VALUES ('Veterans Issues');
INSERT INTO TAG(T_NAME) VALUES ('Women''s issues');
INSERT INTO TAG(T_NAME) VALUES ('Youth');


