DROP TABLE EVENTTABLE IF EXISTS;
CREATE TABLE EVENTTABLE (
  E_NAME      VARCHAR(255) NOT NULL UNIQUE,
  E_DESC      VARCHAR(255) NOT NULL,
  E_EMAIL         VARCHAR(255) NOT NULL,
  E_ADDRESS     VARCHAR(255) NOT NULL,
  E_CITY      VARCHAR(255) NOT NULL,
  E_STATE           VARCHAR(255) NOT NULL,
  E_ZIP      VARCHAR(255) NOT NULL,
  E_DATE     VARCHAR(255) NOT NULL,
  E_STIME    VARCHAR(255) NOT NULL,
  E_ETIME    VARCHAR(255) NOT NULL,
  PRIMARY KEY (E_NAME)
);
