DROP TABLE STUDENT IF EXISTS;
CREATE MEMORY TABLE STUDENT(
  S_FNAME           VARCHAR(255) NOT NULL,
  S_LNAME           VARCHAR(255) NOT NULL,
  S_ID              VARCHAR(255) NOT NULL, -- STUDENT ID
  S_MAJOR           VARCHAR(255),
  PRIMARY KEY(S_ID)
);

