DROP TABLE CATEGORY IF EXISTS;
CREATE TABLE CATEGORY (
  C_NAME          VARCHAR(255) UNIQUE NOT NULL,
  PRIMARY KEY (C_NAME)
);

DROP TABLE USERTABLE IF EXISTS;
CREATE TABLE USERTABLE (
  U_ID            INTEGER NOT NULL AUTO_INCREMENT(1, 1),
  U_USERNAME      VARCHAR(255) NOT NULL UNIQUE,
  U_EMAIL         VARCHAR(255) NOT NULL UNIQUE,
  U_FIRSTNAME     VARCHAR(255) NOT NULL,
  U_LASTNAME      VARCHAR(255) NOT NULL,
  U_DOB           DATE NOT NULL,
  U_JOINDATE      DATE NOT NULL,
  U_PASSWORD      VARCHAR(255) NOT NULL,
  U_PASSWORDHASH  VARCHAR(255) NOT NULL,
  PRIMARY KEY (U_ID)
);

DROP TABLE THREAD IF EXISTS;
CREATE TABLE THREAD (
  T_ID            INTEGER NOT NULL AUTO_INCREMENT (1, 1),
  T_CREATOR       INTEGER NOT NULL,
  T_CREATIONTIME  TIME NOT NULL,
  T_SUBJECT       VARCHAR(255) NOT NULL,
  T_CATEGORY      VARCHAR(255) NOT NULL,
  PRIMARY KEY (T_ID),
  FOREIGN KEY (T_CREATOR) REFERENCES USERTABLE
);

DROP TABLE POST IF EXISTS;
CREATE TABLE POST (
  P_ID            INTEGER NOT NULL AUTO_INCREMENT (1, 1),
  P_CONTENT       LONGVARCHAR NOT NULL,
  P_CREATED       DATETIME NOT NULL,
  P_THREAD        INTEGER NOT NULL,
  P_USER          NUMBER NOT NULL,
  P_PARENT        NUMBER,
  PRIMARY KEY (P_ID),
  FOREIGN KEY (P_THREAD) REFERENCES THREAD,
  FOREIGN KEY (P_PARENT) REFERENCES POST,
  FOREIGN KEY (P_USER) REFERENCES USERTABLE,
);
